### ISSUE TITLE
phpbb3.3.0 error just after installation

### ISSUE THREAD

**Issue by dav01it** [Gsere/phpbb-telegram-notifier#1]
on phpbb 3.3.0 installs but I get error just after installation: alle extensions automatically disabled.

**Comment by dav01it** [comment]
Details:
Eccezione: The file "/web/htdocs/www.f.eu/home/forum/ext/gsere/telegram/config/services.yml" does not contain valid YAML: The reserved indicator "@" cannot start a plain scalar; you need to quote the scalar at line 5 (near "- @request").

#0 /web/htdocs/www.f.eu/home/forum/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(117): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->loadFile('/web/htdocs/www...')
#1 /web/htdocs/www.f.eu/home/forum/phpbb/extension/di/extension_base.php(99): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('services.yml')
#2 /web/htdocs/www.f.eu/home/forum/phpbb/extension/di/extension_base.php(63): phpbb\extension\di\extension_base->load_services(Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#3 /web/htdocs/www.f.eu/home/forum/vendor/symfony/dependency-injection/Compiler/MergeExtensionConfigurationPass.php(71): phpbb\extension\di\extension_base->load(Array, Object(Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationContainerBuilder))
#4 /web/htdocs/www.f.eu/home/forum/vendor/symfony/http-kernel/DependencyInjection/MergeExtensionConfigurationPass.php(39): Symfony\Component\DependencyInjection\Compiler\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#5 /web/htdocs/www.f.eu/home/forum/vendor/symfony/dependency-injection/Compiler/Compiler.php(140): Symfony\Component\HttpKernel\DependencyInjection\MergeExtensionConfigurationPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#6 /web/htdocs/www.f.eu/home/forum/vendor/symfony/dependency-injection/ContainerBuilder.php(789): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
#7 /web/htdocs/www.f.eu/home/forum/phpbb/di/container_builder.php(203): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#8 /web/htdocs/www.f.eu/home/forum/common.php(115): phpbb\di\container_builder->get_container()
#9 /web/htdocs/www.f.eu/home/forum/adm/index.php(23): require('/web/htdocs/www...')
#10 {main}

**Comment by dav01it** [comment]
Added quotes but now...

Fatal error: Declaration of gsere\telegram\notification\method\telegram::is_available() must be compatible with phpbb\notification\method\messenger_base::is_available(?phpbb\notification\type\type_interface $notification_type = NULL) in /web/htdocs/www.f.eu/home/forum/ext/gsere/telegram/notification/method/telegram.php on line 227
